### ISSUE TITLE
Ruby 2.2 changes

### ISSUE THREAD

**Issue by tak1n** [rubysl/rubysl-pathname#5]
For reference see https://github.com/ruby/ruby/blob/v2_2_0/NEWS#L181-L184

- [x] Pathname#/ is aliased to Pathname#+.
- [x] Pathname#birthtime

**Comment by YorickPeterse** [comment]
Fixed in 1d9e31ccfcabd98ea8b421ceec6f5dea780aad05 and fa8167b753537472f0d16c1de8de645f33652756.
